export enum industry {
  ASP = 'ASP',

  DATA_TELECOM = 'DATA_TELECOM',

  ERP = 'ERP',

  GOVERNMENT_MILITARY = 'GOVERNMENT_MILITARY',

  LARGE_ENTERPRISE = 'LARGE_ENTERPRISE',

  MANAGEMENT_ERP = 'MANAGEMENT_ERP',

  MANAGEMENT_ISV = 'MANAGEMENT_ISV',

  MSP = 'MSP',

  NON_MANAGEMENT_ISV = 'NON_MANAGEMENT_ISV',

  SERVICE_PROVIDER = 'SERVICE_PROVIDER',

  WIRELESS_INDUSTRY = 'WIRELESS_INDUSTRY',

  SMALL_MEDIUM_ENTERPRISE = 'SMALL_MEDIUM_ENTERPRISE',

  STORAGE_EQUIPMENT = 'STORAGE_EQUIPMENT',
}
