export enum source {
  NONE = 'NONE',

  COLD_CALL = 'COLD_CALL',

  ADVERTISEMENT = 'ADVERTISEMENT',

  ONLINE_STORE = 'ONLINE_STORE',

  EXTERNAL_REFERENCE = 'EXTERNAL_REFERENCE',

  PARTNER = 'PARTNER',

  PUBLIC_RELATION = 'PUBLIC_RELATION',

  CHAT = 'CHAT',

  INSTAGRAM = 'INSTAGRAM',

  FACEBOOK = 'FACEBOOK',

  WEB_RESEARCH = 'WEB_RESEARCH',
}
