export enum source {
  NONE = 'NONE',

  ADVERTISEMENT = 'ADVERTISEMENT',

  COLD_CALL = 'COLD_CALL',

  EMPLOYEE_REFERRAL = 'EMPLOYEE_REFERRAL',

  EXTERNAM_REFERRAL = 'EXTERNAM_REFERRAL',

  ONLINE_STORE = 'ONLINE_STORE',

  PARTNER = 'PARTNER',

  PUBLIC_RELATIONS = 'PUBLIC_RELATIONS',

  SALES_EMAIL_ALIAS = 'SALES_EMAIL_ALIAS',

  SEMINAR_PARTNER = 'SEMINAR_PARTNER',

  INTERNAL_PARTNER = 'INTERNAL_PARTNER',

  TRADE_SHOW = 'TRADE_SHOW',

  WEB_RESEARCH = 'WEB_RESEARCH',

  WEB_CASES = 'WEB_CASES',

  WEB_MAIL = 'WEB_MAIL',

  CHAT = 'CHAT',

  TWITTER = 'TWITTER',

  FACEBOOK = 'FACEBOOK',

  INSTAGRAM = 'INSTAGRAM',

  OTHER_SOCIAL_MEDIA = 'OTHER_SOCIAL_MEDIA',
}
