export enum stage {
  QUALIFICATION = 'QUALIFICATION',

  NEED_ANALYSIS = 'NEED_ANALYSIS',

  VALUE_PROPOSTITON = 'VALUE_PROPOSTITON',

  IDENTIFY_DECISION_MAKERS = 'IDENTIFY_DECISION_MAKERS',

  PROPOSAL = 'PROPOSAL',

  PRICE_QUOTE = 'PRICE_QUOTE',

  NEGOTIATION = 'NEGOTIATION',

  REVIEW = 'REVIEW',

  CLOSED_WON = 'CLOSED_WON',

  CLOSED_LOST = 'CLOSED_LOST',

  CLOSED_LOST_TO_COMPETITION = 'CLOSED_LOST_TO_COMPETITION',
}
