export enum status {
  ATTEMPTED_TO_CONTACT = 'ATTEMPTED_TO_CONTACT',

  CONTACT_IN_FUTURE = 'CONTACT_IN_FUTURE',

  CONTACTED = 'CONTACTED',

  JUNK_LEAD = 'JUNK_LEAD',

  LOST_LEAD = 'LOST_LEAD',

  NOT_CONTRACTED = 'NOT_CONTRACTED',

  PRE_QUALIFIED = 'PRE_QUALIFIED',

  NOT_QUALIFIED = 'NOT_QUALIFIED',

  CANCELLED = 'CANCELLED',
}
