package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllPropertiesEquals(Lead expected, Lead actual) {
        assertLeadAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAllUpdatablePropertiesEquals(Lead expected, Lead actual) {
        assertLeadUpdatableFieldsEquals(expected, actual);
        assertLeadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadAutoGeneratedPropertiesEquals(Lead expected, Lead actual) {
        assertThat(expected)
            .as("Verify Lead auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableFieldsEquals(Lead expected, Lead actual) {
        assertThat(expected)
            .as("Verify Lead relevant properties")
            .satisfies(e -> assertThat(e.getFirst_name()).as("check first_name").isEqualTo(actual.getFirst_name()))
            .satisfies(e -> assertThat(e.getLast_name()).as("check last_name").isEqualTo(actual.getLast_name()))
            .satisfies(e -> assertThat(e.getCompany()).as("check company").isEqualTo(actual.getCompany()))
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getFax()).as("check fax").isEqualTo(actual.getFax()))
            .satisfies(e -> assertThat(e.getWebsite()).as("check website").isEqualTo(actual.getWebsite()))
            .satisfies(e -> assertThat(e.getLead_source()).as("check lead_source").isEqualTo(actual.getLead_source()))
            .satisfies(e -> assertThat(e.getLead_status()).as("check lead_status").isEqualTo(actual.getLead_status()))
            .satisfies(e -> assertThat(e.getIndustry()).as("check industry").isEqualTo(actual.getIndustry()))
            .satisfies(e -> assertThat(e.getNo_of_emp()).as("check no_of_emp").isEqualTo(actual.getNo_of_emp()))
            .satisfies(e -> assertThat(e.getAnnual_revenue()).as("check annual_revenue").isEqualTo(actual.getAnnual_revenue()))
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getSocial_media()).as("check social_media").isEqualTo(actual.getSocial_media()))
            .satisfies(e -> assertThat(e.getMedia_handle_id()).as("check media_handle_id").isEqualTo(actual.getMedia_handle_id()))
            .satisfies(e -> assertThat(e.getStreet()).as("check street").isEqualTo(actual.getStreet()))
            .satisfies(e -> assertThat(e.getCity()).as("check city").isEqualTo(actual.getCity()))
            .satisfies(e -> assertThat(e.getState()).as("check state").isEqualTo(actual.getState()))
            .satisfies(e -> assertThat(e.getZipcode()).as("check zipcode").isEqualTo(actual.getZipcode()))
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getLead_image()).as("check lead_image").isEqualTo(actual.getLead_image()))
            .satisfies(
                e ->
                    assertThat(e.getLead_imageContentType())
                        .as("check lead_image contenty type")
                        .isEqualTo(actual.getLead_imageContentType())
            )
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadUpdatableRelationshipsEquals(Lead expected, Lead actual) {}
}
